### ISSUE TITLE
How can  I add red point in the bottom item?

### ISSUE THREAD

**Issue by LeaderChange** [Ashok-Varma/BottomNavigation#1]
When a new message pullsh to app, I want show something (just like red point number) in my bottom item what should I do?

**Comment by Ashok-Varma** [comment]
you can download the library and customise the layouts based on your requirements.
That's a good feature may be i will implement in late releases. But now there are some high priority features, i need to push to library.

**Comment by igor-brishkoski** [comment]
@LeaderChange I needed that functionality too, opened up a PR for @Ashok-Varma that address this problem

**Comment by Ashok-Varma** [comment]
@LeaderChange @igor-brishkoski 
I will check the code to night and update library by this weekend (2 days more).

**Comment by igor-brishkoski** [comment]
you mean branch of master instead of forking?

**Comment by Ashok-Varma** [comment]
@igor-brishkoski yes, so it's easy to compare and maintain stuff. I pinged you check your mail once.

**Comment by asebak** [comment]
this would be great to have.

**Comment by Ashok-Varma** [comment]
@asebak @igor-brishkoski @LeaderChange 
Done the changes you can use badges by importing library 1.1.0
