### ISSUE TITLE
items from menu resource

### ISSUE THREAD

**Issue by satti8893** [Ashok-Varma/BottomNavigation#103]
Currently we can add items manually. But is there anyway i can add menu resource xml file to add items?

**Comment by Ashok-Varma** [comment]
no that is not possible. menu item limit the compatibility of library so we didn't include them

**Comment by LOG-TAG** [comment]
it will be grateful if we get like this app:bbn_entries="@menu/bottombar_menu_4items" https://github.com/sephiroth74/Material-BottomNavigation
