### ISSUE TITLE
Thanks for the great library. i just want to ask that Can i increase size of Bottombar Icons?

### ISSUE THREAD

**Issue by Kunal8337** [Ashok-Varma/BottomNavigation#105]
Issue 1 : I want a bit bigger icons in Bottom Navigation Bar. Is it Possible to do it programmatically in current version? 

Issue 2 : can i use only icons.? i don't want name with Icons. can we do it?

please reply ASAP. I am in the middle of it. 
Thank You.

**Comment by Ashok-Varma** [comment]
that pull request i will merge on sunday. then you can just use icons

**Comment by Kunal8337** [comment]
Thanks a lot.
And what about the size of icons.. can we increase the size of it?
Once you are done on Sunday , can you send me a latest version of gradle ?

**Comment by Ashok-Varma** [comment]
yes icon size override the dimens value

https://github.com/Ashok-Varma/BottomNavigation/blob/master/bottom-navigation-bar/src/main/res/values/dimens.xml
