### ISSUE TITLE
How can I set the BadgeItem like a dot rather than a textview?

### ISSUE THREAD

**Issue by clj12081103** [Ashok-Varma/BottomNavigation#109]
How can I set the BadgeItem like a dot rather than a textview?

**Comment by rpandey91** [comment]
Can you please explain the issue?

**Comment by clj12081103** [comment]
I want to set the BadgeItem like a little dot without the number.

**Comment by rpandey91** [comment]
Can you provide an image for better understanding ?

**Comment by clj12081103** [comment]
![image](https://cloud.githubusercontent.com/assets/16871234/24342743/51c2beb4-12f5-11e7-80b5-d12cc0e9c8c2.png)        like this

**Comment by rpandey91** [comment]
ok, give me some time, i'll provide the solution for this.

**Comment by clj12081103** [comment]
thanks

**Comment by Ashok-Varma** [comment]
@rpandey91 thanks for the support

**Comment by rpandey91** [comment]
@Ashok-Varma I have committed the code for the above feature, please have a look..

**Comment by echozheng1** [comment]
I updated to 1.4.1. Why can not it? Is the code not yet submitted?

**Comment by Ashok-Varma** [comment]
@echozheng1 not merged yet

**Comment by Pompoml** [comment]
When plan merger

**Comment by Ashok-Varma** [comment]
merge done. this weekend i will release new version with some more fixes like color white

**Comment by Ashok-Varma** [comment]
released 1.4.3
