### ISSUE TITLE
Elevation and Shadow support

### ISSUE THREAD

**Issue by jt-gilkeson** [Ashok-Varma/BottomNavigation#11]
Per the material design spec this component should have a default elevation of 8dp and cast a shadow upwards on to the content above it - it doesn't seem to do that currently regardless of elevation being set in the layout or in code.

**Comment by Ashok-Varma** [comment]
@jt-gilkeson Elevation an shadow support is only available for android Lollipop and above. This release i am adding it mostly by monday i will release new update.

**Comment by Ashok-Varma** [comment]
@jt-gilkeson closing this, i pushed the code but final release will be on monday mostly
