### ISSUE TITLE
Rotation bug (possibly related to state saving)

### ISSUE THREAD

**Issue by zoltanf** [Ashok-Varma/BottomNavigation#111]
Sometimes when the device get's rotated several times fast it happens that the tabs get doubled or even tripled.

Here is an example:
![screenshot_2017-03-27-13-48-13](https://cloud.githubusercontent.com/assets/1464667/24355203/50f8f412-12f5-11e7-890d-d57cedc46532.jpg)

Here is another one:
![screenshot_2017-03-27-13-43-37](https://cloud.githubusercontent.com/assets/1464667/24355292/9e591e12-12f5-11e7-815b-81dc4cd91fbe.jpg)

Here is the code I'm using to initialise the view:
```        
// Tabs and texts
mTabNavigationBar
       .addItem(new BottomNavigationItem(R.drawable.icv_tab_description, getString(R.string.desc_segment_1)))
       .addItem(new BottomNavigationItem(R.drawable.icv_tab_conditions, getString(R.string.desc_segment_2)))
       .addItem(new BottomNavigationItem(R.drawable.icv_tab_info, getString(R.string.desc_segment_3)))
       .setBarBackgroundColor(R.color.mg_white)
       .setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener() {
                    @Override
                    public void onTabSelected(int position) {
                        // Hide all other
                        for (int i = 0; i < 3; i++) {
                            if (i != position) mDescTextViews[i].setVisibility(View.GONE);
                        }

                        // Make sure this one visible
                        mDescTextViews[position].setVisibility(View.VISIBLE);
                    }

                    @Override
                    public void onTabUnselected(int position) {

                    }

                    @Override
                    public void onTabReselected(int position) {

                    }
                })
                .initialise();
```

Thank you for your effort.

**Comment by Ashok-Varma** [comment]
this is not a library bug. you are adding items on every rotation. So those keep on increasing. 

2 solutions

1. don't add items on rotation. (If you are save your fragment state)
2. clear the items before adding new ones. (If you need fresh fragments)

Please check the sample app

**Comment by zoltanf** [comment]
Wish I would agree with you (it would been an easy fix) but it's not true. The tabs are added only once on view creation (the view is re-created on rotation).

**Comment by Ashok-Varma** [comment]
please add the line 
`mTabNavigationBar.clearAll();
`
before
```
// Tabs and texts
mTabNavigationBar
       .addItem
```

and let me know the results => you are calling addItem on rotation on existing bottombar thats the bug thank-you.
