### ISSUE TITLE
White color for setInActiveColor and setInActiveColor does not work!

### ISSUE THREAD

**Issue by Gamabunta94** [Ashok-Varma/BottomNavigation#115]
White color for tabs doesn't work because the function that parse color return -1 if the color was not found but white color in Android have -1 value!

I'm sorry, I don't speak English very well!

From my activity set -> bottomNavigationItem.setInActiveColor("#FFFFFF");

In your BottomNavigationItem class:

    /**
     * @param context to fetch color
     * @return in-active color (or) -1 if no color is specified
     */
    protected int getInActiveColor(Context context) {
        if (this.mInActiveColorResource != 0) {
            return ContextCompat.getColor(context, mInActiveColorResource);
        } else if (!TextUtils.isEmpty(mInActiveColorCode)) {
            return Color.parseColor(mInActiveColorCode); // IF WHITE RETUN -1
        } else if (this.mInActiveColor != 0) {
            return mInActiveColor;
        } else {
            return -1; // Wrong value
        }
    }

**Comment by Ashok-Varma** [comment]
@Gamabunta94 thanks for the report i completely forgot about this. I will fix it in the next release

**Comment by Ashok-Varma** [comment]
@Gamabunta94 done in 1.4.3
