### ISSUE TITLE
BottomNavigationBar.selectTab(int position) dont callback the OnTabSelectedListener.onTabUnselected

### ISSUE THREAD

**Issue by treycc** [Ashok-Varma/BottomNavigation#119]
you may check, i'm not sure it's kind of bug or design

**Comment by Ashok-Varma** [comment]
@treycc on selection one of these will be called onTabSelected, onTabUnselected, onTabReselected

**Comment by whb7762300** [comment]
I foud the same problem,onTabSelected will callback ,but onTabUnselected not callback sometimes
