### ISSUE TITLE
CoordinatorLayout support

### ISSUE THREAD

**Issue by jt-gilkeson** [Ashok-Varma/BottomNavigation#12]
Per the material design spec:
The bottom navigation bar can appear and disappear dynamically upon scrolling:

Scrolling downward hides the bottom navigation bar
Scrolling upward reveals it

Should work like the FAB or toolbar where you can set an attribute and have it translate itself in and out of the view.

**Comment by Ashok-Varma** [comment]
@jt-gilkeson it is already doing that right. it auto-matically hides/un-hides on scrolling

**Comment by jt-gilkeson** [comment]
@Ashok-Varma Do you have an example of how to enable that?  I have it in an activity that has a coordinatorlayout with a toolbar that hides when I scroll, but don't know how to get BottomNavigation to do that also.

**Comment by Ashok-Varma** [comment]
@jt-gilkeson 
1) this should be direct child to Co-ordinatorLayout
2) need to use nestedscrollview instead of scrollview (any view which is subclass to nestedscrollchild works i. e recyclerview, nestedscrollview ..etc)

**Comment by jt-gilkeson** [comment]
@Ashok-Varma Ahh that must be the problem, I have a relativelayout inside of coordinatorLayout.  Thanks for the explanation.

**Comment by Ashok-Varma** [comment]
@jt-gilkeson 
welcome,
i am closing this issue for now. If you have any issue even after doing that feel free to reopen the issue and comment.
