### ISSUE TITLE
can't find class ShapeBadgeItem...

### ISSUE THREAD

**Issue by hanqing1028** [Ashok-Varma/BottomNavigation#122]
hi, thank u for your BottomNacigation ,its awesome!
Now , i want to add a red dot shaped badge into my bottomitem,just like samle.Just a red dot ,without text.
However, i can't find class ShapeBadageitem in my project which is supported in your Sample like this:
`import com.ashokvarma.bottomnavigation.ShapeBadgeItem;`
`ShapeBadgeItem circularBadgeItem, sqaureBadgeItem;`
` circularBadgeItem =   new ShapeBadgeItem()
                //.setBorderWidth(8)
                .setBackgroundColorResource(R.color.red)
                .setDimen(8) // the size to badge in dp
                .setShape(ShapeBadgeItem.CIRCLE) // Choose between ShapeBadgeItem.CIRCLE or ShapeBadgeItem.SQUARE
                .setMargins(0, 2, 4, 0) // left, top, right, bottom
                .setHideOnSelect(autoHide.isChecked());`
`addItem(new BottomNavigationItem(R.drawable.ic_book_white_24dp, "Books").setActiveColorResource(R.color.teal).setShapeBadgeItem(circularBadgeItem))`

Is ShapeBadgeItem-function disabled in 1.4.1?Or i use the wrong way?Maybe it's only exsist in Sample Projest...?
My english is not good ,but i hope you understand.Thank you~

**Comment by Ashok-Varma** [comment]
it's present in 1.4.2 i will update read me
