### ISSUE TITLE
about number in the top right corner of the icon

### ISSUE THREAD

**Issue by shuimuqinghua** [Ashok-Varma/BottomNavigation#126]
Excuse me,  i want to know,this project can support number in the top right corner of the icon, like wechat？

------------------------------

I'm sorry. I found the badge! I can use the badge in the initialization,but how can I update the badge text when i do something? I can't find the mothed!

Hope you can help me, Thanks!

**Comment by Ashok-Varma** [comment]
please check the sample

```java
TextBadgeItem textBadgeItem = new TextBadgeItem()
                .setBorderWidth(4)
                .setBackgroundColorResource(R.color.blue)
                .setText("" + lastSelectedPosition)
                .setHideOnSelect(autoHide.isChecked());
```
assign badge to BottomNavigationItem before init
 
and you can update textBadgeItem anytime. just call the methods you need it will automaticaaly update
