### ISSUE TITLE
style is error

### ISSUE THREAD

**Issue by hanhailong** [Ashok-Varma/BottomNavigation#129]
![image](https://user-images.githubusercontent.com/4241807/27271119-7262ed6e-54f5-11e7-8599-2a263c760147.png)

the style of badge is error，the Gravity.Top | Gravity.RIGHT is invalid.  version is 1.4.3

**Comment by Ashok-Varma** [comment]
use
```java
 Gravity.Top | Gravity.START
```

instead

**Comment by hanhailong** [comment]
**Gravity.Top | Gravity.START**

this don't work

**Comment by Ashok-Varma** [comment]
can you please submit your code. for the badge
