### ISSUE TITLE
Hope to add a method that sets the Icon size

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [Ashok-Varma/BottomNavigation#137]
bottomNavigationBar.setMode(BottomNavigationBar.MODE_FIXED_NO_TITLE);
        bottomNavigationBar.setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_STATIC);
        bottomNavigationBar.addItem(new BottomNavigationItem(R.mipmap.a1, "home").setInactiveIconResource(R.mipmap.aa1))
                .addItem(new BottomNavigationItem(R.mipmap.b1, "tree").setInactiveIconResource(R.mipmap.bb1))
                .addItem(new BottomNavigationItem(R.mipmap.c1, "show").setInactiveIconResource(R.mipmap.cc1))
                .addItem(new BottomNavigationItem(R.mipmap.d1, "my").setInactiveIconResource(R.mipmap.dd1))
                .initialise();

ICON is too small after use,My picture size is normal.

The size is set to a fixed value,
When add and remove an Item, the width of Item should not be fixed and should be divided according to the width of the screen

   @Override
    protected void setNoTitleIconContainerParams(FrameLayout.LayoutParams layoutParams) {
        layoutParams.height = getContext().getResources().getDimensionPixelSize(R.dimen.fixed_no_title_icon_container_height);
        layoutParams.width = getContext().getResources().getDimensionPixelSize(R.dimen.fixed_no_title_icon_container_width);
    }
    @Override
    protected void setNoTitleIconParams(LayoutParams layoutParams) {
        layoutParams.height = getContext().getResources().getDimensionPixelSize(R.dimen.fixed_no_title_icon_height);
        layoutParams.width = getContext().getResources().getDimensionPixelSize(R.dimen.fixed_no_title_icon_width);
    }

**Comment by Ashok-Varma** [comment]
can you post the icon size. Because these are as recommended by the Google and since you are using only 4 tab items, there is no way that icon will be small.

Issue can be
1) Your Icon might have two much padding in the file. (i.e free space)

please attach your icon and as well as your bottom nav screenshot with layout bounds enabled

**Comment by AndroidJohnsonWang** [comment]
My solution is to rewrite the dimens attribute to solve this problem, my Icon does not meet the Google recommended standards, but this is my company decided to use the icon, I can not change this, is now rewriting the following two attributes solved problem:
 <dimen name="fixed_no_title_icon_height">42dp</dimen>
    <dimen name="fixed_no_title_icon_width">42dp</dimen>
Thank you.

**Comment by Ashok-Varma** [comment]
Good to know you have done it. 
But this library clearly focuses on following google guideLines. Made in such away that people who needs other than default can customise using dimens files. But for most(>99%) who are looking for default behaviour, this should be as clean as possible without any Confusions.

Thanks
