### ISSUE TITLE
Can we set the custom view to bottom layout or margin ?

### ISSUE THREAD

**Issue by yan493483722** [Ashok-Varma/BottomNavigation#142]
for example : I  want to change this xml file "fixed_bottom_navigation_item"  to custom layout ,Because the image too close to TextView. In Other language ,they too close . Hope can provide  channel to custom view Or set Margin  Between ImageView and TextView . thanks.

**Comment by Ashok-Varma** [comment]
you can import the project and change the layout for custom behaviours.
Similar Enhancement was requested check if that will solve your needs => #141

**Comment by yan493483722** [comment]
According you advice and the issue #141 advice. I override those dimensions in my project , it works . thanks a lot.
this is my dimensions:
 <dimen name="fixed_label_active">12sp</dimen>
 <dimen name="fixed_height_bottom_padding">7dp</dimen>
