### ISSUE TITLE
Fab can't put above bottom bar after running app

### ISSUE THREAD

**Issue by SailFlorve** [Ashok-Varma/BottomNavigation#147]
![qq 20170821181553](https://user-images.githubusercontent.com/25448499/29515005-2bf7ca6e-869d-11e7-9ce5-f2bc43665e70.png)

**Comment by SailFlorve** [comment]
when I scroll recyclerView one and then the bottom bar hide and shown, it works fine.

**Comment by ahmadmust8** [comment]
you have to use it in this way : 
```  bottomNavigationBar.setFab(fab)```
