### ISSUE TITLE
version2.0.3

### ISSUE THREAD

**Issue by chshp1234** [Ashok-Varma/BottomNavigation#154]
我把版本2.0.2升级到2.0.3会出现问题
![image](https://user-images.githubusercontent.com/31475629/31753291-3a1f0320-b4c2-11e7-8893-0ec90a0ef1e9.png)

**Comment by Ashok-Varma** [comment]
That might be issue with support libraries. Which support library are you using ??

**Comment by chshp1234** [comment]
26.0.2,
compile 'com.android.support:appcompat-v7:26.0.2'
        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:recyclerview-v7:26.0.2'
        compile 'com.android.support:cardview-v7:26.0.2'

**Comment by Ashok-Varma** [comment]
Try the new 26.1.0 support-lib version. 
Even then if it is not working remove the library and check. So that we can conform whether the issue is with the library

**Comment by chshp1234** [comment]
找到问题了，解决了，多谢回答！！
