### ISSUE TITLE
Badge cut off on phones

### ISSUE THREAD

**Issue by Phoca** [Ashok-Varma/BottomNavigation#157]
Hi everyone,

The badge is cut off to the right when using the library with the following settings and configuration:
- Smartphone (no Tablet) in portrait mode
- Mode set to FIXED_NO_TITLE
- 5 Items displayed

I reproduced the issue in your sample app. A screenshot is attached so you can see what I mean.  
![image](https://user-images.githubusercontent.com/3438255/33930760-47e39550-dfee-11e7-9129-825909984634.png)

I'm trying to fix it and create a PR.

**Comment by Ashok-Varma** [comment]
You can change the size of the badge item to fix that.

**Comment by Phoca** [comment]
I'm using a HTC one m8, which has a Full HD display on 5 inches diagonal size, so not really low dpi.
Removing the padding in the `fixed_bottom_navigation_item.xml` layout file fixed the problem for me. Since the container has a fixed width and the content is centered, do I miss something or is it safe to just remove the padding? It looks good on my phone at least.
See [this commit ](https://github.com/Phoca/BottomNavigation/commit/6a1e6b41260d552894518109d0dd37cae32f3936).

**Comment by Ashok-Varma** [comment]
removing padding might fix the issue but the component will no longer follow the material guidelines. in the given constraints we can't do much. you can try decreasing the size of the badge. thankyou
