### ISSUE TITLE
how to change the icon's width?

### ISSUE THREAD

**Issue by arronvera** [Ashok-Varma/BottomNavigation#159]
how to change the icon's width?

**Comment by Ashok-Varma** [comment]
Icons width is as per google guidelines. if you want small size you can add padding to icon image itself, check if your icon has paddings and remove them to make it big

**Comment by arronvera** [comment]
I want to make it bigger

**Comment by Ashok-Varma** [comment]
you can remove padding from the icon image to make it larger.

This is good tool to generate icons the way you like
https://romannurik.github.io/AndroidAssetStudio/icons-generic.html
