### ISSUE TITLE
how to check why bottom bar became double

### ISSUE THREAD

**Issue by ntaloventi** [Ashok-Varma/BottomNavigation#163]
i have no ide why some time bottombar items became double?
sry if my english not well
[https://drive.google.com/open?id=187ahT9wYb3FPzabx_A44sf1UeMlIpq4v](https://drive.google.com/open?id=187ahT9wYb3FPzabx_A44sf1UeMlIpq4v)

**Comment by Ashok-Varma** [comment]
may be you are adding items multiple times (addItem(......)). If so please do clearAll() before reading items

**Comment by ntaloventi** [comment]
sry late resp, i'm sure just call once, badge are change during api request, can i know how to log or test for debug proccess, thanks in advance

**Comment by Ashok-Varma** [comment]
Try calling clearAll() before adding items. If it solves the bug then code is being called more than once.

If that solution didn't solve the issue then please share your code and also the method in which you wrote the code.

**Comment by ntaloventi** [comment]
ty, i will try ur recomendation
