### ISSUE TITLE
Distance between icon and text does not look right

### ISSUE THREAD

**Issue by jt-gilkeson** [Ashok-Varma/BottomNavigation#17]
I think there is an issue with the layout for the icon and text for fixed mode - specifically it looks like there is much less distance between the bottom of the icon and the top of the text than the spec shows. 

I think this fixes it:

   FrameLayout
        android:layout_width="@dimen/fixed_icon_badge_grid_width"
     **android:layout_height="30dp"**
     **android:paddingTop="6dp"**
        android:layout_gravity="center_horizontal|top"

   ImageView
            android:id="@+id/fixed_bottom_navigation_icon"
            android:layout_width="@dimen/fixed_icon_grid"
            android:layout_height="@dimen/fixed_icon_grid"
            **android:layout_gravity="top|center_horizontal"**
            android:gravity="center"
            android:scaleType="fitXY"

**Comment by jt-gilkeson** [comment]
Created a pull request with the fix for this

**Comment by Ashok-Varma** [comment]
@jt-gilkeson thankyou very much for the support. 
But don't create new issue for these, once a pull request is created you can give the explanation there itself. it will be easy to track and maintain
Thank You
