### ISSUE TITLE
Is It possible with this Lib?

### ISSUE THREAD

**Issue by kushanshah11** [Ashok-Varma/BottomNavigation#173]
How can i do like this with this lib?

![test1](https://user-images.githubusercontent.com/18567763/40420702-c9ff31b6-5ea6-11e8-94a1-2e98609ce9fa.PNG)
![test2](https://user-images.githubusercontent.com/18567763/40420703-ca2c3bd4-5ea6-11e8-97ea-2a9dcc701cce.PNG)

**Comment by Ashok-Varma** [comment]
It's not yet possible with this lib
