### ISSUE TITLE
Why is there an inverted triangle in the transparent background?

### ISSUE THREAD

**Issue by liu1070832898** [Ashok-Varma/BottomNavigation#175]
![fdh2 vk p kf5np8 oh g9h](https://user-images.githubusercontent.com/29189440/41264118-8f345012-6e1d-11e8-99f6-ae7a8cb10253.png)

**Comment by Ashok-Varma** [comment]
I think it's because of android system shadow. 

1. Try adding bnbElevation=0 in your xml to BottomNavigationBar.
2. If you are not using xml for you can add "bottom_navigation_elevation" to your dimens file with 0 as value
