### ISSUE TITLE
MODE_FIXED_NO_TITLE

### ISSUE THREAD

**Issue by likealeodog** [Ashok-Varma/BottomNavigation#177]
In this mode, the circle badge in the top right corner of the home icon on the bottom navigation bar is cut.

**Comment by likealeodog** [comment]
@Ashok-Varma Hello!See the image,the place where I painted the red circle is what I said.Just a small problem.
 
![20180710224228](https://user-images.githubusercontent.com/17841723/42517967-8f0b8f88-8493-11e8-9c0f-78468fd8c02b.png)

**Comment by TsuiYC** [comment]
fixed_bottom_navigation_item.xml/shifting_bottom_navigation_item.xml
Delete (paddingLeft&paddingRight) of the first FrameLayout.

**Comment by TsuiYC** [comment]
@Ashok-Varma The problem is not on the device. When you use more than 5 items, this will also appear.
