### ISSUE TITLE
Got cut on title name bottom bar

### ISSUE THREAD

**Issue by fajaranugrah** [Ashok-Varma/BottomNavigation#178]
hello sir can you help me how to fixed this
![image](https://user-images.githubusercontent.com/38461162/42122737-13ffa4ea-7c79-11e8-9ea9-2d7aa9cade15.png)
i want put text string "Requests" but i try show "Re-"
thank you

i try on your apps demo but got cut on using "Mode Fixed"
![device-2018-07-02-104411](https://user-images.githubusercontent.com/38461162/42142978-298a3ca4-7de5-11e8-8aba-7d20eec5d2d0.png)
![device-2018-07-02-104437](https://user-images.githubusercontent.com/38461162/42142979-29bc857e-7de5-11e8-8310-5c95f3ae943d.png)

**Comment by Ashok-Varma** [comment]
@fajaranugrah according to material design guidelines. We shouldn't use long names in bottom navigation. In sample i placed it to check the limits of Library

1. Never use bottom navigation if you have more than 5 items. [Refer](https://material.io/design/components/bottom-navigation.html#usage)
2. [Refer the text labels section in this](https://material.io/design/components/bottom-navigation.html#anatomy)

**Comment by fajaranugrah** [comment]
but only one sentence is reduced like "Requests", may you help me because i
already use BottomNavigation but i am confused to change the icon
thank you

**Comment by Ashok-Varma** [comment]
@fajaranugrah how many tabs are you using in bottom sheet ??

One thing you can try is to change the text size you can override the text sizes from the library

**Comment by fajaranugrah** [comment]
5 tabs
how to change the text size?

**Comment by Ashok-Varma** [comment]
[Check these dimens](https://github.com/Ashok-Varma/BottomNavigation/blob/master_v2/bottom-navigation-bar/src/main/res/values/dimens.xml)

just add dimens in your project with same name and the value you need. It will be overridden automatically

**Comment by fajaranugrah** [comment]
thanks sir its work
