### ISSUE TITLE
Get item's view

### ISSUE THREAD

**Issue by mitsest** [Ashok-Varma/BottomNavigation#179]
## Question

- [x] Wiki Home (https://github.com/Ashok-Varma/BottomNavigation/wiki)
- [x] Customisations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
- [x ] Behaviour and Animations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Behaviour-and-Animations-Settings)
- [x] Badges (https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges)
- [x] Fab & SnackBar (https://github.com/Ashok-Varma/BottomNavigation/wiki/FAB-&-SnackBar)

- [x] None of those answer my question

Hello!

I 'm currently implementing a walkthrough utility for an application. It is required to create a spotlight-like view and shed the spotlight on one of bottom navigation items. In order to do this, I have to get the item's view.

Is fork the only solution? You have package-private access on 
BadgeItem getBadgeItem() {
        return mBadgeItem;
    }

so I can't even get the badge view from BadgeItem (WeakReference<BadgeTextView> mTextViewRef)

Any help will be appreciated.

Thanks!

**Comment by Ashok-Varma** [comment]
@mitsest sorry, we are not exposing the views. So we can keep the library clean and also to avoid confusion to the users.

yeah, if only method needs to be exposed. i recommend you to fork the library and do the changes needed.
