### ISSUE TITLE
Bug on label naming

### ISSUE THREAD

**Issue by fajaranugrah** [Ashok-Varma/BottomNavigation#181]
the bug its first times open the apps label naming bottom navigation to small but if i click the bottom tab he back to normal

![image](https://user-images.githubusercontent.com/38461162/43242735-55b395ac-90d5-11e8-89f4-4cdb4299934e.png)

![image](https://user-images.githubusercontent.com/38461162/43242801-aee4f90e-90d5-11e8-82ca-82b0a820a30e.png)

like this

Version com.ashokvarma.android:bottom-navigation-bar:2.0.4
Device Google Nexus 5
OS 4.4.4

thank you

**Comment by Ashok-Varma** [comment]
@fajaranugrah  thats an feature not a bug. Please check [this Link](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations) fo rreferance
