### ISSUE TITLE
Set Current Item

### ISSUE THREAD

**Issue by Deandrew007** [Ashok-Varma/BottomNavigation#182]
Hey, I understand that you want the library to be independent of Fragment implementation.
 However, my first fragment isn't visible unless another tab is clicked, then reselect the first tab and the fragment is shown. Any possible suggestions?

**Comment by Ashok-Varma** [comment]
you can try this after initialise().
```java
bottomNavigationBar.selectTab(lastSelectedPosition, true)
```

But, Can you publish your code. you might be adding listener after init().
