### ISSUE TITLE
how to cancle the click effect，when you click tab,the   background will be circle

### ISSUE THREAD

**Issue by LLQQHH** [Ashok-Varma/BottomNavigation#186]
## Question

- [ ] Wiki Home (https://github.com/Ashok-Varma/BottomNavigation/wiki)
- [ ] Customisations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
- [ ] Behaviour and Animations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Behaviour-and-Animations-Settings)
- [ ] Badges (https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges)
- [ ] Fab & SnackBar (https://github.com/Ashok-Varma/BottomNavigation/wiki/FAB-&-SnackBar)

- [ ] None of those answer my question

**Comment by LLQQHH** [comment]
sorry，my English is poor，i don't want the water ripple when i click the item.but can't cancel that effect.

**Comment by LLQQHH** [comment]
![image](https://user-images.githubusercontent.com/19651932/50394623-bc2d8000-0799-11e9-859f-280599a54bd7.png)

**Comment by Ashok-Varma** [comment]
@LLQQHH this library is as per material design guidelines. Any personalisation can be made by overriding the xmls
