### ISSUE TITLE
My label does not appear in full when the text length is more than 9

### ISSUE THREAD

**Issue by jofifora** [Ashok-Varma/BottomNavigation#192]
My label does not appear in full when the text length is more than 9

**Comment by Ashok-Varma** [comment]
How many tabs You have in total ??

**Comment by jofifora** [comment]
I have 4 tabs in my navigation..

**Comment by jofifora** [comment]
im using xiaomi redmi 3s (android 6.0.1, API 23)

**Comment by Ashok-Varma** [comment]
can you attach screenshots and also code

**Comment by jofifora** [comment]
this one when i using virtual devices nexus 5 x API 19
![screenshot_1535649956](https://user-images.githubusercontent.com/8015222/44868486-8251de80-acbd-11e8-9766-906799b15a47.png)

and this when i using xiaomi redmi 3s API 23 (physical device)
![screenshot_2018-08-31-01-12-34-170_com tempjo kupangevent](https://user-images.githubusercontent.com/8015222/44868964-efb23f00-acbe-11e8-8190-50d3f68a2127.png)

this is the Code:
java file :
`bottomNavigationBar = findViewById(R.id.navigationBar);
        bottomNavigationBar
                .addItem(new BottomNavigationItem(R.drawable.ic_home_black_24dp, getResources().getString(R.string.home)))
                .addItem(new BottomNavigationItem(R.drawable.ic_place_black_24dp, getResources().getString(R.string.events)))
                .addItem(new BottomNavigationItem(R.drawable.ic_dashboard_black_24dp, getResources().getString(R.string.organizers)))
                .addItem(new BottomNavigationItem(R.drawable.ic_account_circle_black_24dp, getResources().getString(R.string.me)).setBadgeItem(badgeNotif)))
                .initialise();`


layout:
`<com.ashokvarma.bottomnavigation.BottomNavigationBar
        android:id="@+id/navigationBar"
        app:bnbMode="mode_fixed"
        app:bnbElevation="8dp"
        app:bnbBackgroundStyle="background_style_static"
        app:bnbBackgroundColor="@color/primaryColor"
        app:bnbActiveColor="@color/color_white"
        app:bnbInactiveColor="@android:color/darker_gray"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintVertical_weight="0"
        android:layout_marginEnd="0dp"
        android:layout_marginStart="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"/>`

string.xml:
`<string name="events">Events</string>
    <string name="home">Home</string>
    <string name="organizers">Organizers</string>
    <string name="me">Me</string>`

**Comment by Ashok-Varma** [comment]
WE are supposed to use short labels - [Material Design Guidelines](https://material.io/design/components/bottom-navigation.html#anatomy)

But you can try one of these
1. use MODE_SHIFTING
2. you can change text size from dimens.xml (just override them => use same name and give what dimen you need in your project dimens file)

**Comment by jofifora** [comment]
Thank you very much..
I prefer to change dimens file.. and finally succeded..
