### ISSUE TITLE
Why the color of barbackground and Active exchange? 

### ISSUE THREAD

**Issue by 1-riverfish** [Ashok-Varma/BottomNavigation#193]
## Question

- [yes ] Wiki Home (https://github.com/Ashok-Varma/BottomNavigation/wiki)
- [yes ] Customisations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
- [ yes] Behaviour and Animations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Behaviour-and-Animations-Settings)
- [ no] Badges (https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges)
- [ no] Fab & SnackBar (https://github.com/Ashok-Varma/BottomNavigation/wiki/FAB-&-SnackBar)

- [ ] None of those answer my question

**Comment by 1-riverfish** [comment]
![color_exchange](https://user-images.githubusercontent.com/27009694/44624601-10783e80-a925-11e8-8088-6485f44bf840.PNG)

**Comment by 1-riverfish** [comment]
<com.ashokvarma.bottomnavigation.BottomNavigationBar
        android:id="@+id/bottom_navigation_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:bnbActiveColor="#FFFFFF"
        app:bnbInactiveColor="#303F9F"
        app:bnbBackgroundColor="#3F51B5"
        app:layout_constraintBottom_toBottomOf="parent"
       />
Here is my settings

**Comment by Ashok-Varma** [comment]
Go through this : [wiki](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations#code-snippet-example-2)
