### ISSUE TITLE
firstPosition  question

### ISSUE THREAD

**Issue by jjjjbababy** [Ashok-Varma/BottomNavigation#198]
bottomNavigationBar.addItem(new BottomNavigationItem(R.drawable.home_icon_selected, getString(R.string.news))
                .setInactiveIconResource(R.drawable.home_icon_normal))
                .addItem(new BottomNavigationItem(R.drawable.ask_icon_selected, getString(R.string.ask))
                        .setInactiveIconResource(R.drawable.ask_icon_normal))
                .addItem(new BottomNavigationItem(R.drawable.mine_icon_selected, getString(R.string.mine))
                        .setInactiveIconResource(R.drawable.mine_icon_normal))
                .setFirstSelectedPosition(firstPosition);
bottomNavigationBar.initialise();
bottomNavigationBar.setTabSelectedListener(
                new BottomNavigationBar.SimpleOnTabSelectedListener() {
                    @Override
                    public void onTabSelected(int position) {
                        super.onTabSelected(position);
                        FragmentTransaction ft = manager.beginTransaction();
                        hideAllFragments(ft);
                        switch (position) {
                            case 0:
                                if (homeFragment == null) {
                                    homeFragment = new HomeFragment();
                                    ft.add(R.id.fl_container, homeFragment);
                                } else {
                                    ft.show(homeFragment);
                                }
                                break;
                            case 1:
                                if (checkLogin()) {
                                    if (listFragment == null) {
                                        listFragment = new ListFragment();
                                        ft.add(R.id.fl_container, listFragment);
                                    } else {
                                        ft.show(listFragment);
                                    }
                                } else {
                                    startLogin();
                                }

                                break;
                            case 2:
                                if (checkLogin()) {
                                    if (mineFragment == null) {
                                        mineFragment = new MineFragment();
                                        ft.add(R.id.fl_container, mineFragment);
                                    } else {
                                        ft.show(mineFragment);
                                    }
                                } else {
                                    startLogin();
                                }

                                break;
                        }
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commitAllowingStateLoss();
                    }
                }
        );

But method  public void onTabSelected(0) hadn't invoked.
I don't know why..

**Comment by jjjjbababy** [comment]
The callback  position=0 doesn't  invoke

**Comment by Ashok-Varma** [comment]
Because you called initialise before setting listener. Call initialise after listener
