### ISSUE TITLE
Cannot be displayed visually in the activity_main.xml.(Error Message:Failed to instantiate one or more classes)

### ISSUE THREAD

**Issue by yulin1995** [Ashok-Varma/BottomNavigation#201]
## Question

- [ ] Wiki Home (https://github.com/Ashok-Varma/BottomNavigation/wiki)
- [ ] Customisations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
- [ ] Behaviour and Animations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Behaviour-and-Animations-Settings)
- [ ] Badges (https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges)
- [ ] Fab & SnackBar (https://github.com/Ashok-Varma/BottomNavigation/wiki/FAB-&-SnackBar)

- [x] None of those answer my question

**Comment by Ashok-Varma** [comment]
@yulin1995  can you upload code. Or fork this project and try to reproduce it
