### ISSUE TITLE
How does the effect of the bumps come true?

### ISSUE THREAD

**Issue by CotTan** [Ashok-Varma/BottomNavigation#202]
How does the effect of the bumps come true?
As shown：
![default](https://user-images.githubusercontent.com/11958737/47840373-06752f00-ddf1-11e8-937a-19ed6edb7af0.png)
The middle button goes beyond the current BottomNavigationBar.

**Comment by Ashok-Varma** [comment]
Those are not supported by the library as of now

**Comment by CotTan** [comment]
What time is possible？
