### ISSUE TITLE
[BUG] Selected Tab is not updated when "Back" button of the device is pressed 

### ISSUE THREAD

**Issue by ilkerfindik** [Ashok-Varma/BottomNavigation#204]
### **DESCRIPTION**
**To Reproduce**
1- When I am on one activity(Browse Activity),
2- I click a tab for another activity(Saved Activity),
3- Then I go back with the emulator's back button / or with Back buttons on real devices, 
4- See Error

**Expected Behavior** 
Tab should highlight Browse Activity again

**Obtained Result:** 
Saved Activity's tab is still highlighted as active, but actually app has Browse Activity as active activity. (You can see that at some point the video below has TextView saying "Browse Activity", but the Saved tab is active)  

### **VIDEO / SCREENSHOTS**
**GIF Video**
NOTE: The 11 second GIF file repeats here, but here is a video:  
![back](https://user-images.githubusercontent.com/10101121/48666002-904c1a00-eaca-11e8-8b0c-e0d1bbb1347c.gif)

### **DEVICE INFO**
Happens on all devices I tried. Some of these devices include, but are not limited to:
1- [Emulator] - **3.3 inch, WQVGA**, Android **5.1**, **API 22** device,
2- [Tablet Device] - **Samsung SM-P580**, Android **7.0**, **API 24** device,
3- [Phone] - **Samsung SM-J700F**, Android **6.0.1**, **API 23** device

### **ADDITIONAL CONTEXT**
My code setup has as follows: 
1- TabbedAppCompatActivity class -> Extends regular activities with tab initialization on onCreate method. So that every activity that needs to have bottom tab bar will extend TabbedAppCompatActivity instead of regular one.
2- Other activities have no code at all (related to BottomNavigation)

**TabbedAppCompatActivity.kt**
```
abstract class TabbedAppCompatActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {

        val rootItem = this.findViewById<ViewGroup>(android.R.id.content)
        val inflater:LayoutInflater = LayoutInflater.from(baseContext)
        val inflatedView = inflater.inflate(R.layout.bottom_navigation_bar, rootItem, true)

        val bottomNavigationBar = inflatedView.findViewById(R.id.bottom_navigation_bar_element) as BottomNavigationBar

        bottomNavigationBar
                .addItem(BottomNavigationItem(R.drawable.ic_search, R.string.search))
                .addItem(BottomNavigationItem(R.drawable.ic_browse, R.string.browse))
                .addItem(BottomNavigationItem(R.drawable.ic_bookmark, R.string.saved))
                .addItem(BottomNavigationItem(R.drawable.ic_profile, R.string.profile))
                .setMode(BottomNavigationBar.MODE_FIXED)
                .setActiveColor(R.color.darkThemeColor)
                .initialise()

        val intent = intent

        var selectedPosition = intent.getIntExtra("selectedTabIndex", -1)
        if (selectedPosition == -1)
            selectedPosition = 0

        bottomNavigationBar.selectTab(selectedPosition)


        bottomNavigationBar.setTabSelectedListener(object : BottomNavigationBar.OnTabSelectedListener {
            override fun onTabSelected(position: Int) {
                var intent:Intent

                when (position) {
                    0 -> intent = Intent(applicationContext, SearchActivity::class.java)
                    1 -> intent = Intent(applicationContext, BrowseActivity::class.java)
                    2 -> intent = Intent(applicationContext, SavedActivity::class.java)
                    else -> intent = Intent(applicationContext, ProfileActivity::class.java)
                }

                intent.putExtra("selectedTabIndex", position)

                startActivity(intent)
            }

            override fun onTabUnselected(position: Int) {
                
            }

            override fun onTabReselected(position: Int) {

            }

        })

        super.onCreate(savedInstanceState)   
    }
}

```

**Comment by Ashok-Varma** [comment]
@ilkerfindik You are supposed to use the Bottom nav bar in an activity. and on click you need to replace the fragments in the same activity.(1 activity and 4 fragments) 
But you are launching a new activity on tap of BottomNavaBar.

**Comment by ilkerfindik** [comment]
@Ashok-Varma  Can you please give some examples with code? Or better, update the documentation for others as well? Because the documentation isn't that thorough, and your sample app quits the app on pressing Back. 

I couldn't find out how I will write my on tab listener.

**Comment by ilkerfindik** [comment]
@Ashok-Varma Your sample app quits the app on pressing Back

**Comment by Ashok-Varma** [comment]
@ilkerfindik  that's because the fragments are being replaced and that's the intended behaviour.

If you want to go back to old fragment on click of back you can read about (Fragment BackStack)

**Comment by ilkerfindik** [comment]
@Ashok-Varma  I believe wiki/documentation could be improved a little more, not everything is clear to new developers. For example on the wiki we have:
```
Add TabSelectedListener
```
        bottomNavigationBar.setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener(){
            @Override
            public void onTabSelected(int position) {
            }
            @Override
            public void onTabUnselected(int position) {
            }
            @Override
            public void onTabReselected(int position) {
            }
        });
```
all methods are self explanatory
```

The fact that we should be using fragments and not activities is not that clear. And it would be great if the empty definitions were filled out and were complete. 

Anyway, thank you for the support.
