### ISSUE TITLE
how to add a view on bottombar？

### ISSUE THREAD

**Issue by KayeJing** [Ashok-Varma/BottomNavigation#209]
## Question

The_ button is blocked.
![image](https://user-images.githubusercontent.com/10123395/50482494-d4173500-0a21-11e9-8cc4-18b7c0e244ed.png)

**Comment by Ashok-Varma** [comment]
@KayeJing 
If above content is scrollable you can use this. Else you need to give margin to the view with button
'bottomNavigationBar.setAutoHideEnabled(false);'
