### ISSUE TITLE
How to set active and inactive Images with selector of image not color ? or how to set active as well as inactive drawble direct you mention that inactive drable only...

### ISSUE THREAD

**Issue by gauraviqlance** [Ashok-Varma/BottomNavigation#213]
## Question

- [ ] Wiki Home (https://github.com/Ashok-Varma/BottomNavigation/wiki)
- [ ] Customisations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
- [ ] Behaviour and Animations (https://github.com/Ashok-Varma/BottomNavigation/wiki/Behaviour-and-Animations-Settings)
- [ ] Badges (https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges)
- [ ] Fab & SnackBar (https://github.com/Ashok-Varma/BottomNavigation/wiki/FAB-&-SnackBar)

- [ ] None of those answer my question

**Comment by DineshNeupane** [comment]
I also faced the same issue. The mentioned method is not working in latest version.

**Comment by Ashok-Varma** [comment]
Hi Guys can you please share the code that i can look at
