### ISSUE TITLE
bottomItem

### ISSUE THREAD

**Issue by kangshaopeng** [Ashok-Varma/BottomNavigation#214]
If there are 5 tags, the title can only display up to 3 words.

**Comment by Ashok-Varma** [comment]
Yeah the titles in bottom navigation bar according to google design guideline should be small. 
I will have a look at that, Can you share the titles you are setting ?

**Comment by kangshaopeng** [comment]
![1](https://user-images.githubusercontent.com/17898347/59243864-b0991d00-8c44-11e9-9b42-3caa13530159.png)

**Comment by Ashok-Varma** [comment]
Soory @kangshaopeng , Long Titles can't be displayed by the BottomNavigationBar.
