### ISSUE TITLE
Ripple effect background is not changing

### ISSUE THREAD

**Issue by jagadishlakkur** [Ashok-Varma/BottomNavigation#216]
<com.ashokvarma.bottomnavigation.BottomNavigationBar
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            android:layout_alignParentBottom="true"
            app:bnbMode="mode_shifting"
            app:bnbBackgroundStyle="background_style_ripple"
            android:id="@+id/bottom_nv_view"
            >
        </com.ashokvarma.bottomnavigation.BottomNavigationBar>

 the background color is not changing when item is selected... means when  i selected item its should show ripple with diff colors , but is not showing . it showing single color as background for all items

**Comment by Ashok-Varma** [comment]
Hi Jagadish https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations please follow wiki for customisations
