### ISSUE TITLE
FixedMode layout match error

### ISSUE THREAD

**Issue by neabea** [Ashok-Varma/BottomNavigation#225]
I set BottomNavigationBar android:layout_height="100dp"， app:bnbMode="mode_fixed",
and set dimens  <dimen name="fixed_height">100dp</dimen>
but bottombar don't match 100dp ,fixed layout height just keep 56dp ,Why? how to resolve it?

**Comment by neabea** [comment]
set fixed_height dimens 100dp

**Comment by Ashok-Varma** [comment]
Hi @neabea this is as per material design guidelines. It's restricted to 56dp.
