### ISSUE TITLE
Is there a way to decrease font size of the menus?

### ISSUE THREAD

**Issue by pranishres** [Ashok-Varma/BottomNavigation#233]
In some devices, I am facing the incomplete text of menu issue. Is there a way to decrease the font size of the menu?

**Comment by Ashok-Varma** [comment]
Hi @pranishres 

you can override dimens from your project ([library dimens](https://github.com/Ashok-Varma/BottomNavigation/blob/master/bottom-navigation-bar/src/main/res/values/dimens.xml))
