### ISSUE TITLE
The item text didnt hide when i quickly switch between tabs

### ISSUE THREAD

**Issue by nimdanoob** [Ashok-Varma/BottomNavigation#25]
see this screenshot [pic](http://7xq84c.com1.z0.glb.clouddn.com/bug.png)

**Comment by Ashok-Varma** [comment]
@nimdanoob Thanks, i was able to check the issue i will fix and update the library this weekend.

**Comment by Ashok-Varma** [comment]
@nimdanoob pushed latest version with bug fix. You can import 1.2.1 library
