### ISSUE TITLE
Ripple not working when primaryColor is white

### ISSUE THREAD

**Issue by Florianisme** [Ashok-Varma/BottomNavigation#29]
Hi, this is my implementation:

`<com.ashokvarma.bottomnavigation.BottomNavigationBar
android:layout_alignParentBottom="true"
android:id="@+id/bottom_navigation_bar"
android:layout_width="match_parent"
android:layout_height="wrap_content"
app:bnbBackgroundStyle="background_style_static"
app:bnbBackgroundColor="@color/colorPrimary"
app:bnbMode="mode_fixed"/>`

The problem is that no ripple is shown when I select a tab. Only when setting the bnbBackgroundColor to something different, the animation is shown.

**Comment by Ashok-Varma** [comment]
@Florianisme I will look in to the issue and if it is a bug i will try to fix it as soon as possible.
If you can share your code snippet for the bottomTabs setup it would be really helpful.

Thankyou for using the library

**Comment by Florianisme** [comment]
It's the setBottomNavigationBar method at the end of this file https://github.com/Florianisme/Aperture/blob/master/app/src/main/java/com/florianisme/aperture/MainActivity.java

**Comment by Ashok-Varma** [comment]
Which ripple due you need exactly ?? 
https://github.com/Ashok-Varma/BottomNavigation#bottomnavigationbar-customizations
you need to apply app:bnbBackgroundStyle and app:bnbMode according to your requirment

**Comment by Florianisme** [comment]
I just need the normal ripple as if you selected something in android when using the static mode.

**Comment by jt-gilkeson** [comment]
I think I'm seeing the same issue.  In the sample app if you click on MODE_FIXED and BS_STATIC it shows a ripple when you click on an item (as expected).  In my app, I have the following set and don't see a ripple when I select an item.  Same thing if I click the selected item - in the sample app it shows another ripple as feedback, but in mine no feedback is shown.

```
<com.ashokvarma.bottomnavigation.BottomNavigationBar
		android:id="@+id/bottom_navigation_bar"
		android:layout_alignParentBottom="true"
		android:layout_gravity="bottom"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		app:bnbBackgroundColor="@color/default_white"
		app:bnbActiveColor="@color/primary_pink"
		app:bnbInactiveColor="@color/kindof_grey"
		app:bnbMode="mode_fixed"/>

```

**Comment by Ashok-Varma** [comment]
@jt-gilkeson @Florianisme i was able to reproduce this issue.

1) This is only happing when i use xml attributes for mode and background_style . Some code issue with xml attributes. Thanks for reporting.

You guys can try setting the background style and mode in code for now. I will look in to this weird issue

**Comment by jt-gilkeson** [comment]
Using no xml attributes and setting the mode to fixed in code didn't seem to work for me either :(  I still get no ripples.

**Comment by Ashok-Varma** [comment]
Mode and background_style also remove from XML. it worked.But I will reverify and let you know

**Comment by jt-gilkeson** [comment]
Shouldn't the bottom_navigation_bar_overLay have the following set default in bottom_navigation_bar_container.xml?

`android:visibility="gone"`

Making that change fixed the issue for me.

**Comment by Ashok-Varma** [comment]
both are almost same

**Comment by Ashok-Varma** [comment]
@Florianisme @jt-gilkeson 1.2.2 is out with the fix.
