### ISSUE TITLE
Cut off Text

### ISSUE THREAD

**Issue by Florianisme** [Ashok-Varma/BottomNavigation#30]
Sometimes, the items title is cut off like in this example:
https://goo.gl/photos/aQz2fQ5qHw7aq67S9

The code which has been used is exactly the same as in the previous issue with the missing ripple.

**Comment by Ashok-Varma** [comment]
@Florianisme i will look in to that and before that can you give me your device specifications

**Comment by Florianisme** [comment]
I'm using the OnePlus One 64GB, DPI is set to default and no font settings have been changed

**Comment by Ashok-Varma** [comment]
@Florianisme thank you i will take a look in to the issue.

**Comment by Ashok-Varma** [comment]
@Florianisme fixed the issue today night update will include fixes to both your bugs.
Thanks for your support.

**Comment by Ashok-Varma** [comment]
@Florianisme 1.2.2 is out with the fix.
