### ISSUE TITLE
can help？

### ISSUE THREAD

**Issue by talentsxh** [Ashok-Varma/BottomNavigation#33]
I would like to click on the item to change the picture and title。

**Comment by Ashok-Varma** [comment]
@talentsxh you can do this by setting onTabSelectedListener and write your code in on tabselected

**Comment by talentsxh** [comment]
In the end, I was the one to solve this problem, but I do not know what will be the problem, after all, I just want to change a picture.This should not have any problems. Forgive me for a beginner.  I really appreciate your help.

like this：
public void onTabSelected(int position) {
        switch (position){
            case 0:
                navigationBar.clearAll();
                navigationBar.removeItem(homeNo).removeItem(shareCircleNo).removeItem(myNo)
                             .addItem(homeYes).addItem(shareCircleNo).addItem(myNo)
                             .setFirstSelectedPosition(position).initialise();
                break;
            case 1:
                navigationBar.clearAll();
                navigationBar.removeItem(homeNo).removeItem(shareCircleNo).removeItem(myNo)
                        .addItem(homeNo).addItem(shareCircleYes).addItem(myNo)
                        .setFirstSelectedPosition(position).initialise();
                break;
            case 2:
                navigationBar.clearAll();
                navigationBar.removeItem(homeNo).removeItem(shareCircleNo).removeItem(myNo)
                        .addItem(homeNo).addItem(shareCircleNo).addItem(myYes)
                        .setFirstSelectedPosition(position).initialise();
                break;
            default:
                break;
        }
    }

**Comment by Ashok-Varma** [comment]
@talentsxh my picture you mean icon ??
if you need to change the icon of tab you set different icons for selected and unSelected tabs to the BottomNavigationItem.
_code snippet :_ 
```java
BottomNavigationItem home = new BottomNavigationItem(R.drawable.xxxxx, R.string.xxxxx);
home.setInactiveIconResource(R.drawable.yyyy)
// home.setInactiveIcon(Drawable) you can use either of these methods
```
the default icon will be when selected Tab icon and InactiveIcon will be the unSelected Tab icon
