### ISSUE TITLE
Change Text size

### ISSUE THREAD

**Issue by sicksand** [Ashok-Varma/BottomNavigation#35]
Hi, how do I change textsize?

**Comment by Ashok-Varma** [comment]
@sicksand This feature will reflect in next update mostly tomorrow night. I will ping you once it is done.

**Comment by sicksand** [comment]
Cool! Will close this.

**Comment by Ashok-Varma** [comment]
I will close this once it's done.

**Comment by Ashok-Varma** [comment]
closing this for now .this will be tracked with #38 issue which is like superset to this
