### ISSUE TITLE
How to change Item Icon size, Text size and Badge size, because on my device it's looks very small?

### ISSUE THREAD

**Issue by adilkhan95** [Ashok-Varma/BottomNavigation#38]

**Comment by Ashok-Varma** [comment]
@adilkhan95 those sizes are taken from google material design specs (https://www.google.com/design/spec/components/bottom-navigation.html). in future we might provide a way to change them but for now we will stick with material design guide lines

**Comment by rafakob** [comment]
You can always override those dimensions in your project, eg:

```    <dimen name="badge_text_size">12sp</dimen><!-- 10 -->
    <dimen name="badge_corner_radius">13dp</dimen><!-- 15 -->
    <dimen name="badge_width_padding">4dp</dimen><!-- 4 -->
    <dimen name="badge_height_padding">1dp</dimen><!-- 1 -->
    <dimen name="badge_top_margin">2dp</dimen><!-- 2 -->```

**Comment by Ashok-Varma** [comment]
@rafakob thanks for your support

**Comment by lxnx0** [comment]
Can someone show me how to override these dimensions? I added these value in dimens.xml, but it seems like not working for me.

**Comment by Ashok-Varma** [comment]
after adding these lines you need to modify the values those are the default values so they look same.

Change the values of these as you like and check.

**Comment by lxnx0** [comment]
Is that mean I need to edit the source file instead of just override it with my own dimens.xml file?

**Comment by Ashok-Varma** [comment]
If you don't need animations you can use tab layout for that.

**Comment by JordyCuan** [comment]
@rafakob @Ashok-Varma   Hi, I have an issue, if I set this dimensions values in dimens.xml file and modify the default values I can not see a change. Can you show me how to override these dimensions? Thanks in advance
