### ISSUE TITLE
How to forbidden the Bottom Navigation scroll to hide when pull up the content view

### ISSUE THREAD

**Issue by fishwjy** [Ashok-Varma/BottomNavigation#40]
I know it's a very nice experience to hide the bottom navigation automatically when user go through the content especially the content is a long list.
However, in some project of mine, the user want to fix the bottom navigation.
So how to deal with it? Thanks a lot.

**Comment by fishwjy** [comment]
Oh, I found the answer. If the content view isn't the NestedScrollView, it will be what I want.
But still hope the feature can be set by a function method.

**Comment by Ashok-Varma** [comment]
@fishwjy these are default behaviours of bottomNavBar. you can switch these off any time, by setting the co-ordinator layout behaviours to null

**Comment by Ashok-Varma** [comment]
@fishwjy From version 1.3.0 you can still use RecylerView/NestedScroll View and call setAutoHideEnabled method to disable the feature.
```java
bottomNavigationBar.setAutoHideEnabled(false);
```
