### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by hussam996** [Ashok-Varma/BottomNavigation#42]
![device-2016-06-14-141211](https://cloud.githubusercontent.com/assets/7525662/16041017/e9280048-323b-11e6-90b0-e4bbd2b9e3fc.png)

Strange behavior when I try my app in android 4.1.2 , Am notice when I begin touch inside tab something black line around tab appear..when I finish disappear

**Comment by Ashok-Varma** [comment]
@hussam996 yeah really strange. Let me look in to it.

can i see the code snippet you used ? and is it only occurring in this version(4.1.2) or all pre-lollipop versions
