### ISSUE TITLE
Unable to set colors

### ISSUE THREAD

**Issue by tejalshah84** [Ashok-Varma/BottomNavigation#43]
Hi there - Thanks for the library. I am not able to set custom color to the bottom bar background and icons when active/inactive. The background always is white and the unselect color is always grey.

 bottomNavigation
                .addItem(new BottomNavigationItem(R.drawable.ic_home, "Home"))
                .addItem(new BottomNavigationItem(R.drawable.ic_search, "Search"))
                .addItem(new BottomNavigationItem(R.drawable.ic_settings, "Settings"))
                .initialise();

        bottomNavigation
                .setMode(BottomNavigationBar.MODE_FIXED);
        bottomNavigation
                .setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_STATIC);

        bottomNavigation
                .setActiveColor(R.color.turquoise)
                .setInActiveColor(R.color.white)
                .setBarBackgroundColor(R.color.teal);

**Comment by tejalshah84** [comment]
My color resource file:

<color name="colorPrimary">#a1d5da</color>
    <color name="colorPrimaryDark">#a1d5da</color>
    <color name="colorAccent">@color/white</color>
    <color name="white">#FFFF</color>
    <color name="seagreen">#75ceaf</color>
    <color name="teal">#a1d5da</color>
    <color name="turquoise">#13B1C1</color>

**Comment by tejalshah84** [comment]
My color resource file.....(the tags are closed in my file...needed to paste like this so github retains format)
<color name="turquoise">#13B1C1
<color name="white">#FFFF
<color name="teal">#a1d5da

**Comment by tejalshah84** [comment]
My color resource file.....(the tags are closed in my file...needed to paste like this so github retains format)
name="turquoise" #13B1C1
name="white" #FFFF
name="teal" #a1d5da

**Comment by Ashok-Varma** [comment]
@tejalshah84 thanks for the feedback.

You need to do all the customisation before calling initialise. So you need to add the colors and set modes before calling initialise. Planning to improve this in future versions, i will do it as soon as possible.

**Comment by tejalshah84** [comment]
Thank you Ashok. That worked. I had been struggling with bottom bar for a while, your library works really well.

I intend to have the clicks of the bottom bar associated with fragments. So in the methods onTabSelected, Unselected, etc ...I assume I would go about exchanging and adding fragments.

Also, instead of changing icon color on active, is there any way I can change tab background color in static mode for 3 icons? Maybe add my own xml drawable and assign instead of icon or something?

Thanks for your help again.

**Comment by Ashok-Varma** [comment]
Question 1 :

if you click on tab that was already selected => reselect will be called.
if you select any tab other than selected one => respective selected and unselected will be called.
this is necessary because in many cases people on need to do anything onTabReselect. But if we call select and unselect at that time unnecessary things happen (in your case same fragment will be detached and attached again), so i kept those separately.

Question 2 :
you can also set active and inactive colors to icons. Check documentation.
https://github.com/Ashok-Varma/BottomNavigation#3-colors
https://github.com/Ashok-Varma/BottomNavigation#4-individual-bottomnavigationitem-colors

once you set them there are four different variants available in the library https://github.com/Ashok-Varma/BottomNavigation#bottomnavigationbar-customizations check those and apply mode and background mode based on your requirements.

**Comment by tejalshah84** [comment]
Thank you again for the prompt clarification. For the second question, Sorry I didn't explain the question clearly. I do not want to change the icon color. I want to change the color of the fixed width tab's background color only for the selected tab but want the background color for the unselected tab's to be the original nav bar color. Almost like each tab is a button and I change the button background color on tab select.

**Comment by Ashok-Varma** [comment]
@tejalshah84 currently you cannot do that with this library. A **new background mode** needs to be added in order to do that. I will consider this option soon, but there are other priority features which needs to be completed before this. So, it will take time.

**Comment by tejalshah84** [comment]
Thank you again. Your library works like a charm! Just tested it out.

Is there way I could tweak the code to add this background color myself?

Also if I want to add animation on fragment exchange, I guess I would add to the onTabSelect method.

**Comment by Ashok-Varma** [comment]
- yes fragment animations can be done in onTabSelected.
- you can add new background mode and do the stuff you need in select() and unselect() methods of BottomNavigationTab.java or it's derivatives.

**Comment by tejalshah84** [comment]
Thank you :)
