### ISSUE TITLE
App crashes when using vectors as drawables

### ISSUE THREAD

**Issue by Florianisme** [Ashok-Varma/BottomNavigation#44]
I'm using vectors in my drawable folder and the app crashes when I try setting a vector as a drawable of an BottomNavigationItem like so:

`bottomNavigationBar.addItem(new BottomNavigationItem(getResources().getDrawable(R.drawable.ic_categories), R.string.navigation_categories)).initialise();`

My vector drawable is a normal svg which was converted by AS to the default compiling format:

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0">
    <path
        android:fillColor="#FF000000"
        android:pathData="M3,5L3,7L5,7L5,5L3,5zM7,5L7,7L21,7L21,5L7,5zM3,9L3,11L5,11L5,9L3,9zM7,9L7,11L17,11L17,9L7,9zM3,13L3,15L5,15L5,13L3,13zM7,13L7,15L19,15L19,13L7,13zM3,17L3,19L5,19L5,17L3,17zM7,17L7,19L15,19L15,17L7,17z" />
</vector>
`

**Comment by Ashok-Varma** [comment]
@Florianisme 
i will check the issue. can you post the crash log.

**Comment by jacorpski** [comment]
Instead of using getDrawable(R.drawable.id), then use R.drawable.id instead, it's working fine for me

**Comment by Ashok-Varma** [comment]
@jacorpski other functionalities working fine ? like active color, in-active color and other animations?

I will test vector drawables case this weekend. But just curious how other functionalities are working.

**Comment by jacorpski** [comment]
@Ashok-Varma I haven't seen any problems so far, so it's working fine
