### ISSUE TITLE
BottomNavigationBar.initialise()

### ISSUE THREAD

**Issue by rogerou** [Ashok-Varma/BottomNavigation#48]
private void initScrollTabs(boolean isReFresh) {
        scrollingTabs.setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_STATIC);
        scrollingTabs.setMode(BottomNavigationBar.MODE_FIXED);
        if (!isReFresh) {
            for (BottomNavigationItem item : bottom_list) {
                item.setActiveColor(MainApplication.APP_THEME_COLOR).setInActiveColorResource(R.color.text_color_323232);
                scrollingTabs.addItem(item);
            }
        } else {
            for (BottomNavigationItem item : scrollingTabs.getItems()) {
                item.setActiveColor(MainApplication.APP_THEME_COLOR).setInActiveColorResource(R.color.text_color_323232);

            }
        }
        if (isFirstPage) {
            scrollingTabs.setFirstSelectedPosition(X_tab_position);
            viewPager.setCurrentItem(X_tab_position);
        } else {
            scrollingTabs.setFirstSelectedPosition(0);
            viewPager.setCurrentItem(0);
        }
        scrollingTabs.initialise();
    }

when I initialise the second time , the item's active icon will  dismiss only the inactive icon .I debug and check the code but I can't figure out that.

**Comment by Ashok-Varma** [comment]
@rogerou i didn't quite understand the problem. Can you explain it in breif

**Comment by rogerou** [comment]
@Ashok-Varma  ok, the problem is that when i initialise the bottombar the second time , all the tab will 
only remain the normal state , no seleted or preessed.

**Comment by Ashok-Varma** [comment]
@rogerou call clearAll() before resetting-data something like this.
```java
 private void initScrollTabs(boolean isReFresh) {
    scrollingTabs.clearAll();
    scrollingTabs.setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_STATIC);
    scrollingTabs.setMode(BottomNavigationBar.MODE_FIXED);
    if (!isReFresh) {
        for (BottomNavigationItem item : bottom_list) {
            item.setActiveColor(MainApplication.APP_THEME_COLOR).setInActiveColorResource(R.color.text_color_323232);
            scrollingTabs.addItem(item);
        }
    } else {
        for (BottomNavigationItem item : scrollingTabs.getItems()) {
            item.setActiveColor(MainApplication.APP_THEME_COLOR).setInActiveColorResource(R.color.text_color_323232);

        }
    }
    if (isFirstPage) {
        scrollingTabs.setFirstSelectedPosition(X_tab_position);
        viewPager.setCurrentItem(X_tab_position);
    } else {
        scrollingTabs.setFirstSelectedPosition(0);
        viewPager.setCurrentItem(0);
    }
    scrollingTabs.initialise();
}
```

**Comment by rogerou** [comment]
@Ashok-Varma thanks , I have tried that ,unfortunately, it didn't work but remain blank.

**Comment by rogerou** [comment]
![qq 20160706171806](https://cloud.githubusercontent.com/assets/11498513/16613222/acd7ded8-439d-11e6-8a87-8a9db2052f91.png)  like this.

**Comment by Ashok-Varma** [comment]
@rogerou 
clearAll() clears all the data even the navigationItems saved in my class. so you can reintiliase from scratch. But i see you are using scrollingTabs.getItems() (Custom Method) which if i am correct gives the tabs from libraries ArrayList which is empty. If you Customizing my library then in initialise() method add this at the begining.
```java
        mSelectedPosition = DEFAULT_SELECTED_POSITION;
```
this should slove

**Comment by rogerou** [comment]
@Ashok-Varma  thanks for helping out. I found the problem is that I have set the Default Position but the tabs didn't initialise

 <pre><code>
 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
</code></pre>

I  Commented out this：
 <pre><code>
  if (isFirstPage) {
        scrollingTabs.setFirstSelectedPosition(X_tab_position);
        viewPager.setCurrentItem(X_tab_position);
    } else {
        scrollingTabs.setFirstSelectedPosition(0);
        viewPager.setCurrentItem(0);
    }
</code></pre>
It woks;

**Comment by rogerou** [comment]
@Ashok-Varma  And I found this  
<pre><code>
    if (isInActiveIconSet) {
            StateListDrawable states = new StateListDrawable();
            //works below api 21 ,use bitmapdrawble 
            states.addState(new int[]{android.R.attr.state_selected}, new BitmapDrawable(drawableToBitmap(mCompactIcon)));

            states.addState(new int[]{-android.R.attr.state_selected},
                    mCompactInActiveIcon);
            states.addState(new int[]{},
                    mCompactInActiveIcon);
            iconView.setImageDrawable(states); 

</code></pre>

**Comment by Ashok-Varma** [comment]
@rogerou the fix i told you was bug fix. So, If you do 
```java
        mSelectedPosition = DEFAULT_SELECTED_POSITION;
```
you no need to use clearAll(). So set the fix and remove clearrAll() from your code. That works.

**Comment by Ashok-Varma** [comment]
@rogerou 
the fix which you mentioned is currently working in API 21 and below. There is no issue.

**Comment by rogerou** [comment]
@Ashok-Varma  well,that's nice.

**Comment by Ashok-Varma** [comment]
i will close this once bug fix was released
