### ISSUE TITLE
Using Snackbar

### ISSUE THREAD

**Issue by silverboyir** [Ashok-Varma/BottomNavigation#49]
Hi
how i can use snackbar when using bottom navigation in activity ?
I'm not getting any error , just its not showing , maybe its showing under the bottom bar ?

**Comment by Arlem** [comment]
Hi,
have you tried using a CoordinatorLayout? Snackbar will appear at bottom of the CoordinatorLayout instead of screen.

**Comment by silverboyir** [comment]
Hi
yes , parent of layout is a CoordinatorLayout , and snackbar work in other activities , that dosent have bottom navigation

**Comment by silverboyir** [comment]
This is my layout : 

`<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:background="@drawable/bg"
    android:orientation="vertical"
    tools:context="com.badansaz98.www.badansaz.Programdetail">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="?attr/actionBarSize"
            android:background="@drawable/custom_background_bar"
            android:theme="@style/ToolbarTheme"
            app:titleTextAppearance="@style/Toolbar.TitleText"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            android:layout_gravity="right"
            android:gravity="top|start"
            >
            <TextView
                android:id="@+id/action_bar_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="right"
                android:textColor="@color/white"
                android:textSize="18sp"
                android:text="@string/app_name"
                />

        </android.support.v7.widget.Toolbar>
    </android.support.design.widget.AppBarLayout>
    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        >
        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:id="@+id/placeSnackBar">
                <LinearLayout
                    android:id="@+id/main_layout"
                    android:orientation="vertical"
                    android:layout_width="match_parent"
                    android:layout_marginTop="5dp"
                    android:layout_height="wrap_content">
                        <RelativeLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"

                            >
                            <ImageView
                                android:id="@+id/program_art"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:src="@drawable/select_men"
                                />

                            <LinearLayout
                                android:id="@+id/download_holder"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_alignParentLeft="true"
                                android:layout_alignParentTop="true"
                                android:background="@color/blue"
                                android:paddingTop="3dp"
                                android:paddingBottom="3dp"
                                android:layout_marginTop="15dp"

                                >

                                <TextView
                                    android:id="@+id/download_text_icon"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="@string/fa_download"
                                    android:layout_gravity="center_vertical"
                                    android:textColor="@color/white"
                                    android:paddingRight="5dp"
                                    android:textSize="12sp"/>

                                <TextView
                                    android:id="@+id/download_text"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textColor="@color/white"
                                    android:text="Download"
                                    android:textSize="10sp"
                                    android:paddingRight="5dp"
                                    android:paddingLeft="5dp"
                                    />
                            </LinearLayout>

                            <LinearLayout
                                android:id="@+id/calendar_holder"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_alignParentLeft="true"
                                android:layout_below="@+id/download_holder"
                                android:layout_marginTop="15dp"
                                android:background="@color/blue"
                                android:paddingTop="3dp"
                                android:paddingBottom="3dp"
                                >

                                <TextView
                                    android:id="@+id/day_in_week_icon"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="@string/fa_calendar_o"
                                    android:layout_gravity="center_vertical"
                                    android:textColor="@color/white"
                                    android:paddingRight="5dp"
                                    android:textSize="12sp"/>

                                <TextView
                                    android:id="@+id/day_in_week"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textColor="@color/white"
                                    android:text="Download"
                                    android:textSize="10sp"
                                    android:paddingRight="5dp"
                                    android:paddingLeft="5dp"
                                    />
                            </LinearLayout>

                            <LinearLayout
                                android:id="@+id/price_holder"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_alignParentLeft="true"
                                android:layout_below="@+id/calendar_holder"
                                android:layout_marginTop="15dp"
                                android:background="@color/yellow"
                                android:paddingTop="3dp"
                                android:paddingBottom="3dp"
                                >

                                <TextView
                                    android:id="@+id/price_icon"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="@string/fa_download"
                                    android:layout_gravity="center_vertical"
                                    android:textColor="@color/white"
                                    android:paddingRight="5dp"
                                    android:textSize="12sp"/>

                                <TextView
                                    android:id="@+id/price"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textColor="@color/white"
                                    android:text="Download"
                                    android:textSize="10sp"
                                    android:paddingRight="5dp"
                                    android:paddingLeft="5dp"
                                    />
                            </LinearLayout>
                        </RelativeLayout>
                        <LinearLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:orientation="vertical"
                            android:layout_marginTop="10dp"
                            >
                            <RelativeLayout
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content">

                                <TextView
                                    android:layout_alignParentTop="true"
                                    android:layout_alignParentRight="true"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textSize="26dp"
                                    android:paddingRight="5dp"
                                    android:textColor="@color/white"
                                    android:text="@string/program_description"
                                    />

                                <LinearLayout
                                    android:id="@+id/current_rate"
                                    android:background="@drawable/main_button"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:paddingLeft="15dp"
                                    android:paddingRight="15dp"
                                    android:paddingTop="7dp"
                                    android:paddingBottom="7dp"
                                    android:layout_marginTop="5dp"
                                    android:orientation="horizontal"
                                    android:layout_alignParentLeft="true"
                                    />

                            </RelativeLayout>

                            <TextView
                                android:id="@+id/text_container"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:textSize="12dp"
                                android:paddingRight="5dp"
                                android:textColor="@color/white"
                                />

                            <RelativeLayout
                                android:id="@+id/profile_layout"
                                android:layout_width="match_parent"
                                android:background="@color/white"
                                android:layout_height="110dp"
                                android:layout_marginTop="20dp"
                                >

                                <ImageView
                                    android:id="@+id/profile_image"
                                    android:layout_width="wrap_content"
                                    android:layout_alignParentRight="true"
                                    android:src="@drawable/select_men"
                                    android:layout_height="match_parent" />

                                <TextView
                                    android:layout_marginTop="15dp"
                                    android:id="@+id/profile_name_holder"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:layout_marginRight="20dp"
                                    android:textSize="15dp"
                                    android:text="@string/created_by"
                                    android:layout_toLeftOf="@id/profile_image"
                                    android:layout_alignParentTop="true"
                                    android:textColor="@color/black"
                                    />
                                <TextView
                                    android:layout_marginTop="15dp"
                                    android:id="@+id/profile_name"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textSize="15dp"
                                    android:layout_marginRight="2dp"
                                    android:text="test"
                                    android:layout_toLeftOf="@id/profile_name_holder"
                                    android:layout_alignParentTop="true"
                                    android:textColor="@color/blue"
                                    />

                                <TextView
                                    android:id="@+id/profile_shortdesc"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:textSize="15dp"
                                    android:text="test2"
                                    android:layout_toLeftOf="@id/profile_image"
                                    android:layout_marginRight="20dp"
                                    android:layout_below="@id/profile_name"
                                    android:textColor="@color/black"
                                    android:layout_marginTop="10dp"

                                    />

                            </RelativeLayout>


                            <android.support.v7.widget.RecyclerView
                                android:id="@+id/days"
                                android:layout_marginTop="10dp"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_marginBottom="150dp"
                                />


                        </LinearLayout>
            </LinearLayout>
        </android.support.design.widget.CoordinatorLayout>
    </ScrollView>
    <com.ashokvarma.bottomnavigation.BottomNavigationBar
        android:layout_gravity="bottom"
        android:id="@+id/bottom_navigation_bar"
        android:layout_width="match_parent"
        app:bnbBackgroundColor="@android:color/transparent"
        android:background="@drawable/custom_background_bottom_bar"
        android:layout_height="wrap_content"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="70dp"
        android:layout_marginLeft="10dp"
        android:layout_gravity="bottom|end"
        app:backgroundTint="@color/blue"
        android:src="@drawable/new_program_icon" />
</android.support.design.widget.CoordinatorLayout>
`

**Comment by Arlem** [comment]
I do use snackbars in my app and my xml looks like this:

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:orientation="vertical">
    <FrameLayout
        android:id="@+id/main_container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        tools:context=".activity.MainActivity"
        tools:ignore="MergeRootFrame"/>
    <com.ashokvarma.bottomnavigation.BottomNavigationBar
        android:layout_gravity="bottom"
        android:id="@+id/bottom_navigation_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</LinearLayout>
```
Snackbar appears at bottom of FrameLayout; my CoordinatorLayout has layout_height:match_parent, but I don't know if it matters.
P.S. FrameLayout is the placeholder for fragments, layout is not as simple as it looks.

**Comment by silverboyir** [comment]
Thanks 
this is my layout 
http://codebeautify.org/xmlviewer/cb0f832f
can you please check that and say what is wrong with that ?

**Comment by Arlem** [comment]
http://pastebin.com/ZmB8jERq

I copied (and adapted) your xml and this is the initialization in activity; the snackbar appears at the bottom of the scrollview.

**Comment by Ashok-Varma** [comment]
@Arlem @silverboyir no need of using two co-ordinator layouts. I am pushing an update for the library to night which will take care of all those

**Comment by Ashok-Varma** [comment]
Pushed 1.3.0 to you can use SnackBar with version 1.3.0
