### ISSUE TITLE
Cross-Fade animation switching views?

### ISSUE THREAD

**Issue by amanzan** [Ashok-Varma/BottomNavigation#52]
Would it be possible to add a cross-fade animation when switching views, like it is stated in Material guidelines?

![bottomnav](https://cloud.githubusercontent.com/assets/3911627/16593856/6b648606-42b5-11e6-9dfe-ced668150c07.gif)

**Comment by Ashok-Varma** [comment]
this library is like tabs you need to change the views as user clicks on tabs. you can you fragments and fragment to do this
