### ISSUE TITLE
Change Activity and BottomNavigationBar will reset item 1

### ISSUE THREAD

**Issue by J0R1SK** [Ashok-Varma/BottomNavigation#53]
Hello,

I have a problem with the behaviour of an active element when I'm back to the Activity.

For example, I have a BottomNavigationBar with 5 items in my Activity.
Let's say I click the 4th item of my bar. If I change Activity,  onBackPress, my BottomNavigationBarActivity will still be on my 4th Fragment as expected, but the active item of my bar will be the first one.

The same behaviour appears when I put my app in background and then go back to it.

Any idea how to solve the problem? Am I missing something in onPause / onResume or something?

Here is the initBottomBar() method I call in onCreate() : 

```
public void initBottomBar() {
        // Bottom Bar
        bottomNavigationBar = (BottomNavigationBar) findViewById(R.id.bottom_navigation_bar);
        // Mode
        bottomNavigationBar.setMode(BottomNavigationBar.MODE_FIXED);
        //bottomNavigationBar.setMode(BottomNavigationBar.MODE_SHIFTING);
        // Background
        bottomNavigationBar.setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_STATIC);

        // Auto Hide on Scroll
        bottomNavigationBar.setAutoHideEnabled(false);

        bottomNavigationBar
                .addItem(new BottomNavigationItem(R.drawable.ic_action_a, "A").setActiveColorResource(R.color.active).setInActiveColor(R.color.inactive))
                .addItem(new BottomNavigationItem(R.drawable.ic_action_b, "Mon B").setActiveColorResource(R.color.active).setInActiveColor(R.color.inactive))
                .addItem(new BottomNavigationItem(R.drawable.ic_action_c, "C").setActiveColorResource(R.color.active).setInActiveColor(R.color.inactive))
                .addItem(new BottomNavigationItem(R.drawable.ic_action_d, "D").setActiveColorResource(R.color.active).setInActiveColor(R.color.inactive))
                .addItem(new BottomNavigationItem(R.drawable.ic_action_e, "E").setActiveColorResource(R.color.active).setInActiveColor(R.color.inactive))
                .initialise();

        bottomNavigationBar.setTabSelectedListener(this);
    }
```

**Comment by Ashok-Varma** [comment]
the default behaviour of bottomBar is different. You shouldn't launch a new activity on click of bottom bar item. So, this change won't be done in library. But i can give you some code 
```java

    int lastSelectedPosition = -1;
    int selectedPosition = -1;

    @Override
    protected void onResume() {
        super.onResume();
        if (selectedPosition == 3) {// since you asked for 4th item in bottom bar -> position 3
            if (lastSelectedPosition != -1) {
                bottomNavigationBar.selectTab(lastSelectedPosition);
            }
        }
    }

    @Override
    public void onTabSelected(int position) {
        if (selectedPosition != position) {
            lastSelectedPosition = selectedPosition;
            selectedPosition = position;
        }
//other logic which you do
}
```

**Comment by flameboy** [comment]
You didn't understand, I am not launching an Activity not onClick on a bottomBar item, but inside a Fragment of a selected bottom bar item. But thank you very much for the code, I am sure that it will do the trick!

**Comment by Ashok-Varma** [comment]
@flameboy the behaviour shouldn't be like that can you share me all your activity code all the part related to bottomNavBAr. i.e where are you calling this initBottomBar ..etc.

This code which i gave might solve your problem but might cause performance issues if you don't do it right. just share you code. i will have a look in to that and let you know about the issue

**Comment by flameboy** [comment]
I am calling my initBottomBar() method only in the onCreate() part of my Activity. After, I have only one function that change the content of each tab (with fragments) as you can see in the code below. 

This works really good, and I have for example a list of 10 items in my FragmentTabs4, and when I click on an item, a new Activity is opened that detail this selected item (full screen, without my bottom bar). When I go back to my main Activity with bottomBar, the Fragment is still set to FragmentTabs4, but the bottomBar is reset to the first element. 

```
@Override
    public void onTabSelected(int position) {

        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();

        switch(position) {
            case 0:
                FragmentTabs1 fragmentTabs1 = new FragmentTabs1();
                transaction.replace(R.id.fragment_container, fragmentTabs1);
                break;
            case 1:
                FragmentTabs2 fragmentTabs2 = new FragmentTabs2();
                transaction.replace(R.id.fragment_container, fragmentTabs2);
                break;
            case 2:
                FragmentTabs3 fragmentTabs3 = new FragmentTabs3();
                transaction.replace(R.id.fragment_container, fragmentTabs3);
                break;
            case 3:
                FragmentTabs4 fragmentTabs4 = new FragmentTabs4();
                transaction.replace(R.id.fragment_container, fragmentTabs4);
                break;
            case 4:
                FragmentTabs5 fragmentTabs5 = new FragmentTabs5();
                transaction.replace(R.id.fragment_container, fragmentTabs5);
                break;
        }

        transaction.addToBackStack(null);
        transaction.commit();
    }
```
