### ISSUE TITLE
bottom navigation color

### ISSUE THREAD

**Issue by ambadasgangul** [Ashok-Varma/BottomNavigation#57]
I want to set my own color for bottom navigation background

**Comment by asebak** [comment]
call the function setBarBackgroundColor

**Comment by Ashok-Varma** [comment]
@asebak thanks for the support.
@ambadasgangul as @asebak said you need to use setBarBackgroundColor to set the background color.

For more customization take a look at this [wiki page](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
