### ISSUE TITLE
2 floating action bar

### ISSUE THREAD

**Issue by silverboyir** [Ashok-Varma/BottomNavigation#58]
Hi
thanks for this great lib
i think i found a bug, when i put 2 floating action bar in page , and set them as fab , the top button behaviour very strange and getting a large margin from bottom button when bottom bar is showing   

`

<android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/fab_margin"
        android:layout_gravity="bottom|end"
        app:backgroundTint="@color/blue"
        android:src="@drawable/new_program_icon" />

```
<android.support.design.widget.FloatingActionButton
    android:id="@+id/edit"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginBottom="0dp"
    android:layout_marginEnd="@dimen/fab_margin"
    android:layout_marginLeft="@dimen/fab_margin"
    android:layout_marginRight="0dp"
    android:layout_marginStart="@dimen/fab_margin"
    android:layout_marginTop="0dp"
    android:layout_gravity="top|end"
    app:layout_anchor="@id/fab"
    app:layout_anchorGravity="top"
    app:backgroundTint="@color/yellow"
    android:src="@drawable/edit_icon" />
```

`

![photo_2016-07-19_20-12-31](https://cloud.githubusercontent.com/assets/3395720/16956313/2a0c473c-4ded-11e6-86e7-36d5804b4dc7.jpg)
![photo_2016-07-19_20-12-35](https://cloud.githubusercontent.com/assets/3395720/16956314/2a1595d0-4ded-11e6-90d2-8089937a5bf1.jpg)

**Comment by Ashok-Varma** [comment]
two fabs are not supported yet i need to think of this particular scenario.

**Comment by silverboyir** [comment]
OK , with adding an invisible floating action button , i fixed my problem 

`<android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/fab_margin"
        android:layout_gravity="bottom|end"
        app:backgroundTint="@color/blue"
        android:src="@drawable/new_program_icon" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab_invisible"
        android:layout_width="@dimen/fab_margin"
        android:layout_height="@dimen/fab_margin"
        android:layout_gravity="top|end"
        app:backgroundTint="@color/blue"
        android:visibility="invisible"
        app:layout_anchor="@id/fab"
        app:layout_anchorGravity="top" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/edit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="0dp"
        android:layout_marginEnd="@dimen/fab_margin"
        android:layout_marginLeft="@dimen/fab_margin"
        android:layout_marginRight="0dp"
        android:layout_marginStart="@dimen/fab_margin"
        android:layout_marginTop="0dp"
        android:layout_gravity="top|end"
        app:layout_anchor="@id/fab_invisible"
        app:layout_anchorGravity="top"
        android:visibility="gone"
        app:backgroundTint="@color/yellow"
        android:src="@drawable/edit_icon" />`

and just set first button with setFab() method for bottom navigation bar
