### ISSUE TITLE
More custom style define by users

### ISSUE THREAD

**Issue by WUDehong** [Ashok-Varma/BottomNavigation#60]
This library is cool but it is too narrow.For example, I can't define the active icon,text color and image color can't be defined different, or the users hope only change the text color.  Hope can update in the future.

**Comment by Ashok-Varma** [comment]
next update i will include these features

**Comment by Ashok-Varma** [comment]
All those features are available in latest version [refer documentation](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
