### ISSUE TITLE
Strange colors behaviour

### ISSUE THREAD

**Issue by scame** [Ashok-Varma/BottomNavigation#64]
After screen rotating sometimes I get normal bottom navigation colors (as defined in XML or programmatically) and sometimes active color becomes background and background color becomes active (basically, they get swapped). Additional info: I use AppCompat NoActionBar theme with overrode colors and number of tabs changes dynamically (it's important because color changes occur after number of tabs was changed and followed by config changes, like rotating)

**Comment by Ashok-Varma** [comment]
@scame can you post your Navigation bar code so i can take a look at

**Comment by scame** [comment]
here is the code https://github.com/scame/LightTube/blob/master/app/src/main/java/com/example/scame/lighttube/presentation/activities/TabActivity.java there is no code related to colors, but I tried to use java approach as well as XML to set colors. BTW bottomNavigatonBar.get***Color() methods in onStart always return identical values

**Comment by scame** [comment]
as a workaround, I added these lines to the part (initSignInBottomBar method) where colors problem occurs 
`bottomNavigationBar.setBarBackgroundColor(R.color.colorAccent); // this will be active color
        bottomNavigationBar.setActiveColor(R.color.colorPrimary); // and this is background`
