### ISSUE TITLE
How To Hide Text?

### ISSUE THREAD

**Issue by Kshitij-Jain** [Ashok-Varma/BottomNavigation#67]
I Don't Want Text In Navigation Bar Like Instagram And Also Want To Reduce Size Like It?
How Can I Do It?
Thanks In Advance :)

**Comment by Ashok-Varma** [comment]
if you just want no text then you can set title as empty string (""), but bottom bar won't resize. I will update to support this feature many people are asking this feature.

**Comment by Kshitij-Jain** [comment]
Yeah Sir!
That I Know!
Please Update Sir!
Thanks In Advance :D

**Comment by amanzan** [comment]
it would be great to have this, I agree :)

**Comment by nikunjgundaniya** [comment]
@Ashok-Varma Hey did you get a chance to remove the title & resize the tab accordingly?

**Comment by ShaouCN** [comment]
That's what I want!Hope to update soon.Thanks!

**Comment by Ashok-Varma** [comment]
I am busy with some other works less time  to maintain the library. Some one of you can create a pull request i will update the project. Thanks

**Comment by Ashok-Varma** [comment]
version 2.0.0 has new modes to this. [refer documentation](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)

**Comment by aiynmm** [comment]
I just want to hide the only one label of the tabs and leave the icon alone,  what should I do for this purpose?

**Comment by aiynmm** [comment]
update: 
I find the release v1.4.1 can solve my problem! I don't pass label property use the construtor that only have icon property of BottomNavigationItem!
