### ISSUE TITLE
Bottom Navigation label

### ISSUE THREAD

**Issue by lowfiend** [Ashok-Varma/BottomNavigation#7]
I find 
  labelView.animate().scaleY(1).scaleX(1).setDuration(animationDuration).start();

when selected Is it possible like this?

![Alt text](http://i.imgur.com/a7QhPFi.png?1 "")

thanks

**Comment by Ashok-Varma** [comment]
@lowfiend 
no it is not, we are just animating label i.e title text as per material bottom navigation guidelines

**Comment by lowfiend** [comment]
Because effect is cool. thanks

**Comment by Ashok-Varma** [comment]
yeah but it looks like ios, it confuses Android users and also material design will be mising

**Comment by lowfiend** [comment]
I forgot where I found project with android,so I searching similar with Google,but I found iOS screenshot
