### ISSUE TITLE
from the Activity to jump to the specified fragments

### ISSUE THREAD

**Issue by wei3** [Ashok-Varma/BottomNavigation#71]
There is a demand, from the Activity to jump to the specified fragments,
If (" TAG_TAB_ORDER ". The equals (getIntent () getStringExtra (" tag "))) {
Bottom_navigation_bar_container. SelectTab (1);
} else {
Bottom_navigation_bar_container. SelectTab (0);
}

**Comment by Ashok-Varma** [comment]
it's basicaaly like android tab layout. Below Fragments should be handled by you.
