### ISSUE TITLE
Please remove synthetic methods

### ISSUE THREAD

**Issue by jt-gilkeson** [Ashok-Varma/BottomNavigation#76]
In AS: Analyze, Run inspection by name, Private member access between outer and inner classes
Make the changes it suggests (basically change various fields to package-local instead of private if they are accessed from inner/anonymous classes).

This will lower the method count of the library by eliminating compiler generated synthetic wrapper methods.

For more info see this: 
https://realm.io/news/360andev-jake-wharton-java-hidden-costs-android/

**Comment by Ashok-Varma** [comment]
@jt-gilkeson thanks will look in to that. Great info
