### ISSUE TITLE
Some Content is covered by BottomNavigationBar

### ISSUE THREAD

**Issue by econ0mist** [Ashok-Varma/BottomNavigation#80]
![help](https://cloud.githubusercontent.com/assets/22831799/19378138/fb6d15b4-9225-11e6-92d6-c65941557cf9.png)

Some Content(Green Color) is covered by BottomNavigationBar. Not work NestedScrollView, ScrollView...

**Comment by Ashok-Varma** [comment]
add paading to your recyclerview/nested scroll view : and set cliptoPadding property as false
