### ISSUE TITLE
How to make this scrollable ?

### ISSUE THREAD

**Issue by swetakadam** [Ashok-Varma/BottomNavigation#84]
I have say 15 items in menu .. how can I make it scrollable .. it all appears staggered in avl width on phone

**Comment by Ashok-Varma** [comment]
this shouldn't be used for such use cases max allowed according to google is 5. In case of 15 u can use tab_layout. 

for now library is not supporting scrollable items
Thankyou

**Comment by swetakadam** [comment]
Thanks @Ashok-Varma
