### ISSUE TITLE
how to set space between image and text?

### ISSUE THREAD

**Issue by mawenge** [Ashok-Varma/BottomNavigation#86]
the vertical space between icon and text for a BottomNavigationItem, and other dimension?

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fixed_bottom_navigation_container"
    android:layout_width="match_parent"
    android:layout_height="@dimen/fixed_height"
    android:background="?selectableItemBackgroundBorderless"
    android:paddingBottom="@dimen/fixed_height_bottom_padding"
    android:paddingLeft="@dimen/fixed_width_padding"
    android:paddingRight="@dimen/fixed_width_padding"
    android:paddingTop="@dimen/fixed_height_top_padding_inactive">

    <FrameLayout
        android:layout_width="@dimen/fixed_icon_badge_grid_width"
        android:layout_height="@dimen/fixed_icon_badge_grid_height"
        android:layout_gravity="center_horizontal|top">

        <ImageView
            android:id="@+id/fixed_bottom_navigation_icon"
            android:layout_width="@dimen/fixed_icon_grid"
            android:layout_height="@dimen/fixed_icon_grid"
            android:contentDescription="@string/icon"
            android:layout_gravity="center"
            android:gravity="center"
            android:scaleType="fitXY" />

        <TextView
            android:id="@+id/fixed_bottom_navigation_badge"
            style="@style/BadgeText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="top|end"
            android:gravity="center" />
    </FrameLayout>

    <TextView
        android:id="@+id/fixed_bottom_navigation_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal|bottom"
        android:gravity="center"
        android:includeFontPadding="false"
        android:lines="1"
        android:scaleX="@dimen/fixed_label_active_to_inactive_ratio"
        android:scaleY="@dimen/fixed_label_active_to_inactive_ratio"
        android:textSize="@dimen/fixed_label_active" />

</FrameLayout>`

this is fixed_bottom_navigation_item.xml, I think the padding_bottom is too big for me, is there any method to modify them?

**Comment by Ashok-Varma** [comment]
the padding and other things are as per material design guidelines. you can change them by overriding respective dimens in your project
