### ISSUE TITLE
BadgeItem

### ISSUE THREAD

**Issue by hcadoid** [Ashok-Varma/BottomNavigation#90]
Bottom NavigationBar Adds the BadgeItem and initialized, but badge.show() or badge.hide() ，no effect。
then 
mBottomBar.postDelayed(new Runnable() {
                @Override
                public void run() {
                    if(isNotice){
                        badge.show();
                    }else{
                        badge.hide();
                    }
                }
            },1000);

1 seconds delay can be displayed, why?

**Comment by Ashok-Varma** [comment]
@hcadoid call hide/show on badge, after you can intialise on bottomBar not before that.
