### ISSUE TITLE
Is it possible to disable icon animation?

### ISSUE THREAD

**Issue by amanzan** [Ashok-Varma/BottomNavigation#91]
When any tab is clicked there is an icon animation even in BS_STATIC mode. Is it possible to disable this animation so that the icon remains at the same position and only changes its color?

**Comment by Ashok-Varma** [comment]
It might take some time to add all these. meanwhile you can import library and comment the unwanted code.

**Comment by andrewlu1** [comment]
need it to.please add api to disable the objanim or samply add single mode to have the anim removed.

**Comment by canhuah** [comment]
i also need this function

**Comment by normalhh** [comment]
I need it, too.

**Comment by Ashok-Varma** [comment]
BS_STATIC is related the background changes not icon animation. [refer documentation](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)
If need to change the way animations look you need to change mode. [refer documentation](https://github.com/Ashok-Varma/BottomNavigation/wiki/Customisations)

If BS_STATIC with no animation is what needed. Then TabLayout can be used no need of third party libraries thankyou
