### ISSUE TITLE
how to set the red dot ?

### ISSUE THREAD

**Issue by adbGitHub** [Ashok-Varma/BottomNavigation#95]
How to set the red dot, do not need to remind the number

thank you!

**Comment by csbenz** [comment]
Perhaps you can customize your badge so that it shows a red dot. See https://github.com/Ashok-Varma/BottomNavigation/wiki/Badges

**Comment by Ashok-Varma** [comment]
@csbenz thanks for the help.
@adbGitHub sorry for late reply indeed very late reply
