### ISSUE TITLE
Select Tab by code to fire onTabSelected

### ISSUE THREAD

**Issue by wea1809** [Ashok-Varma/BottomNavigation#96]
first thanks for the library its very useful, second my question is exist a way to fired the onTabSelected event by code?

I use this  bottomNavigationBar.selectTab(0,true); but not works

**Comment by csbenz** [comment]
I think there's a bug: the selectTab() method works except if the first argument is 0.
This needs a fix :)

**Comment by csbenz** [comment]
A quick fix is to do something like:
```
bottomBar.selectTab(1, true);  
bottomBar.selectTab(0, true);
```
to select tab 0.

**Comment by Ashok-Varma** [comment]
@csbenz @wea1809 hai sorry for the late reply but can you guys post your codes here for init bottomnavbar

**Comment by csbenz** [comment]
Here is my initialization, even thought I'm pretty sure the bug comes from the line I referenced in my comment above:
```
bottomBar
                .addItem(new BottomNavigationItem([...]).setBadgeItem(badgeAll))
                .addItem(new BottomNavigationItem([...]).setBadgeItem(badgeTags))
                .addItem(new BottomNavigationItem([...]).setBadgeItem(badgeChar))
                .initialise();

        bottomBar.setTabSelectedListener(this);
        bottomBar.setAutoHideEnabled(false);
        bottomBar.selectTab(1, true);
        bottomBar.selectTab(0, true);

        ViewCompat.setElevation(bottomBar, 5);
```

**Comment by Ashok-Varma** [comment]
@csbenz @wea1809 set tab selected listener before initialise to get the call back.

**Comment by csbenz** [comment]
Hadn't thought about that, I'll try it later on, thanks! :)

**Comment by Ashok-Varma** [comment]
it i not sending callback because there is no listener when you are initialising it. Try that.

As of now i am closing the issue. If it's not working reopen this
