### ISSUE TITLE
Title is truncated (5 items bar)

### ISSUE THREAD

**Issue by Dimezis** [Ashok-Varma/BottomNavigation#98]
Hello. First of all, thank you for the library.
I have a small issue with badge title truncation when there's 5 items in bottom bar.
Please take a look at "Calendar" tab. It can be truncated even more if the screen is small.
Text size is default, icons are vector assets (24x24dp).

![image](https://cloud.githubusercontent.com/assets/1433500/21844081/9325faa8-d7ed-11e6-9283-9a375fc50165.png)

I believe there's enough space to fit the title properly, so I'm wondering if there's a quick workaround I can apply for now, till you fix it. 

Thank you.

**Comment by setoba1192** [comment]
Hi, has you solved it?? I have the same issue.

**Comment by Dimezis** [comment]
@setoba1192 no, I didn't try though.
To be honest I would rather switch for different bottom bar lib, because this one looks as not maintained anymore, and I'm pretty sure it's gonna be faster than trying to workaround some internal bugs.

**Comment by Ashok-Varma** [comment]
it's not a bug those are design limitations for bottom nav bar. you can reduce the text size if you want. copy dimens file from project and add the attrs which ever you want to your dimens file

**Comment by Dimezis** [comment]
Well, if you're talking about some design limitations, then you should know that title shouldn't be shown at all when there are > 3 items in bottom bar. At least Google says that. 

But I was asked to implement it this way, and the fact that your lib supports it, was the only reason I used it.
So I would still ask you to remove that extra padding from title, or whatever is there and allow to fit 1-2 characters more, if there's this much space.

**Comment by Ashok-Varma** [comment]
@Dimezis people asked me to allow it so i gave it as a feature. So people with small title can use it.

This is a open source library people can customise to there needs. it's just copy the dimens file and override the changes you need in your project. Just one line of work. You can customise the library as you need

**Comment by canberkcakmak** [comment]
@Ashok-Varma  hi, i'm looking to change text size, I dont know how can i override dimens file? pls help me. By the way thanks for great lib.

**Comment by Ashok-Varma** [comment]
@canberkcakmak 
check the value you need to change from this file https://github.com/Ashok-Varma/BottomNavigation/blob/master/bottom-navigation-bar/src/main/res/values/dimens.xml

in your dimens file write a new dimen => with the same name and with value you want
