### ISSUE TITLE
Add customization in more than 5 items

### ISSUE THREAD

**Issue by andres-vasquez** [Ashok-Varma/BottomNavigation#99]
Hi, 
I've already used your library to build a customization feature with drag and drop navigation items like iOS.

[https://developer.xamarin.com/recipes/ios/content_controls/tab_bar/specify_customizable_tab_bar_buttons/Images/Picture_1.png](url) # iOS reference

I want to share this code because I think this could be useful for some devs like me. 
So If you want, I can make a fork from your repo and  make a pull request later.

Regards.
Andres
![image](https://cloud.githubusercontent.com/assets/5274840/22555758/2c43b21c-e93b-11e6-8ce1-e6f4b2aaed06.png)

**Comment by Ashok-Varma** [comment]
Bottom Navigation bar is not good for more than 5 items navigation. In that case google recommend navigation bar

**Comment by andres-vasquez** [comment]
My fix doesn't include more than 5 items in navigation bar. It uses the 5th item as "More" and then includes all other items in a ListView as iOS pattern. 

 If you don't consider include that option in your repo is OK.
